repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black
      args: [integration, reflex, tests]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.244
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.313
    hooks:
    - id: pyright
      args: [integration, reflex, tests]
      language: system

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
      exclude: '^reflex/reflex.py'
